package org.bouncycastle.asn1.x9;

import androidx.exifinterface.media.ExifInterface;
import org.bouncycastle.asn1.u;

/* JADX INFO: loaded from: classes10.dex */
public interface g {
    public static final u ansi_X9_42;
    public static final u ansi_X9_62;
    public static final u c2onb191v4;
    public static final u c2onb191v5;
    public static final u c2onb239v4;
    public static final u c2onb239v5;
    public static final u c2pnb163v1;
    public static final u c2pnb163v2;
    public static final u c2pnb163v3;
    public static final u c2pnb176w1;
    public static final u c2pnb208w1;
    public static final u c2pnb272w1;
    public static final u c2pnb304w1;
    public static final u c2pnb368w1;
    public static final u c2tnb191v1;
    public static final u c2tnb191v2;
    public static final u c2tnb191v3;
    public static final u c2tnb239v1;
    public static final u c2tnb239v2;
    public static final u c2tnb239v3;
    public static final u c2tnb359v1;
    public static final u c2tnb431r1;
    public static final u cTwoCurve;
    public static final u characteristic_two_field;
    public static final u dhEphem;
    public static final u dhHybrid1;
    public static final u dhHybrid2;
    public static final u dhHybridOneFlow;
    public static final u dhOneFlow;
    public static final u dhSinglePass_cofactorDH_sha1kdf_scheme;
    public static final u dhSinglePass_stdDH_sha1kdf_scheme;
    public static final u dhStatic;
    public static final u dhpublicnumber;
    public static final u ecdsa_with_SHA1;
    public static final u ecdsa_with_SHA2;
    public static final u ecdsa_with_SHA224;
    public static final u ecdsa_with_SHA256;
    public static final u ecdsa_with_SHA384;
    public static final u ecdsa_with_SHA512;
    public static final u ellipticCurve;
    public static final u gnBasis;
    public static final u id_dsa;
    public static final u id_dsa_with_sha1;
    public static final u id_ecPublicKey;
    public static final u id_ecSigType;
    public static final u id_fieldType;
    public static final u id_kdf_kdf2;
    public static final u id_kdf_kdf3;
    public static final u id_publicKeyType;
    public static final u mqv1;
    public static final u mqv2;
    public static final u mqvSinglePass_sha1kdf_scheme;
    public static final u ppBasis;
    public static final u prime192v1;
    public static final u prime192v2;
    public static final u prime192v3;
    public static final u prime239v1;
    public static final u prime239v2;
    public static final u prime239v3;
    public static final u prime256v1;
    public static final u primeCurve;
    public static final u prime_field;
    public static final u tpBasis;
    public static final u x9_42_schemes;
    public static final u x9_44;
    public static final u x9_44_components;
    public static final u x9_63_scheme;

    static {
        u uVar = new u("1.2.840.10045");
        ansi_X9_62 = uVar;
        u uVarW = uVar.w("1");
        id_fieldType = uVarW;
        prime_field = uVarW.w("1");
        u uVarW2 = uVarW.w(ExifInterface.GPS_MEASUREMENT_2D);
        characteristic_two_field = uVarW2;
        gnBasis = uVarW2.w("3.1");
        tpBasis = uVarW2.w("3.2");
        ppBasis = uVarW2.w("3.3");
        u uVarW3 = uVar.w("4");
        id_ecSigType = uVarW3;
        ecdsa_with_SHA1 = uVarW3.w("1");
        u uVarW4 = uVar.w(ExifInterface.GPS_MEASUREMENT_2D);
        id_publicKeyType = uVarW4;
        id_ecPublicKey = uVarW4.w("1");
        u uVarW5 = uVarW3.w(ExifInterface.GPS_MEASUREMENT_3D);
        ecdsa_with_SHA2 = uVarW5;
        ecdsa_with_SHA224 = uVarW5.w("1");
        ecdsa_with_SHA256 = uVarW5.w(ExifInterface.GPS_MEASUREMENT_2D);
        ecdsa_with_SHA384 = uVarW5.w(ExifInterface.GPS_MEASUREMENT_3D);
        ecdsa_with_SHA512 = uVarW5.w("4");
        u uVarW6 = uVar.w(ExifInterface.GPS_MEASUREMENT_3D);
        ellipticCurve = uVarW6;
        u uVarW7 = uVarW6.w("0");
        cTwoCurve = uVarW7;
        c2pnb163v1 = uVarW7.w("1");
        c2pnb163v2 = uVarW7.w(ExifInterface.GPS_MEASUREMENT_2D);
        c2pnb163v3 = uVarW7.w(ExifInterface.GPS_MEASUREMENT_3D);
        c2pnb176w1 = uVarW7.w("4");
        c2tnb191v1 = uVarW7.w("5");
        c2tnb191v2 = uVarW7.w("6");
        c2tnb191v3 = uVarW7.w("7");
        c2onb191v4 = uVarW7.w("8");
        c2onb191v5 = uVarW7.w("9");
        c2pnb208w1 = uVarW7.w("10");
        c2tnb239v1 = uVarW7.w("11");
        c2tnb239v2 = uVarW7.w("12");
        c2tnb239v3 = uVarW7.w("13");
        c2onb239v4 = uVarW7.w("14");
        c2onb239v5 = uVarW7.w("15");
        c2pnb272w1 = uVarW7.w("16");
        c2pnb304w1 = uVarW7.w("17");
        c2tnb359v1 = uVarW7.w("18");
        c2pnb368w1 = uVarW7.w("19");
        c2tnb431r1 = uVarW7.w("20");
        u uVarW8 = uVarW6.w("1");
        primeCurve = uVarW8;
        prime192v1 = uVarW8.w("1");
        prime192v2 = uVarW8.w(ExifInterface.GPS_MEASUREMENT_2D);
        prime192v3 = uVarW8.w(ExifInterface.GPS_MEASUREMENT_3D);
        prime239v1 = uVarW8.w("4");
        prime239v2 = uVarW8.w("5");
        prime239v3 = uVarW8.w("6");
        prime256v1 = uVarW8.w("7");
        id_dsa = new u("1.2.840.10040.4.1");
        id_dsa_with_sha1 = new u("1.2.840.10040.4.3");
        u uVar2 = new u("1.3.133.16.840.63.0");
        x9_63_scheme = uVar2;
        dhSinglePass_stdDH_sha1kdf_scheme = uVar2.w(ExifInterface.GPS_MEASUREMENT_2D);
        dhSinglePass_cofactorDH_sha1kdf_scheme = uVar2.w(ExifInterface.GPS_MEASUREMENT_3D);
        mqvSinglePass_sha1kdf_scheme = uVar2.w("16");
        u uVar3 = new u("1.2.840.10046");
        ansi_X9_42 = uVar3;
        dhpublicnumber = uVar3.w("2.1");
        u uVarW9 = uVar3.w(ExifInterface.GPS_MEASUREMENT_3D);
        x9_42_schemes = uVarW9;
        dhStatic = uVarW9.w("1");
        dhEphem = uVarW9.w(ExifInterface.GPS_MEASUREMENT_2D);
        dhOneFlow = uVarW9.w(ExifInterface.GPS_MEASUREMENT_3D);
        dhHybrid1 = uVarW9.w("4");
        dhHybrid2 = uVarW9.w("5");
        dhHybridOneFlow = uVarW9.w("6");
        mqv2 = uVarW9.w("7");
        mqv1 = uVarW9.w("8");
        u uVar4 = new u("1.3.133.16.840.9.44");
        x9_44 = uVar4;
        u uVarW10 = uVar4.w("1");
        x9_44_components = uVarW10;
        id_kdf_kdf2 = uVarW10.w("1");
        id_kdf_kdf3 = uVarW10.w(ExifInterface.GPS_MEASUREMENT_2D);
    }
}
