package e9;

import androidx.exifinterface.media.ExifInterface;
import org.bouncycastle.asn1.u;

/* JADX INFO: loaded from: classes7.dex */
public interface e {
    public static final u gmss;
    public static final u gmssWithSha1;
    public static final u gmssWithSha224;
    public static final u gmssWithSha256;
    public static final u gmssWithSha384;
    public static final u gmssWithSha512;
    public static final u mcEliece;
    public static final u mcElieceCca2;
    public static final u mcElieceFujisaki;
    public static final u mcElieceKobara_Imai;
    public static final u mcEliecePointcheval;
    public static final u newHope;
    public static final u qTESLA;
    public static final u qTESLA_p_I;
    public static final u qTESLA_p_III;
    public static final u rainbow;
    public static final u rainbowWithSha1;
    public static final u rainbowWithSha224;
    public static final u rainbowWithSha256;
    public static final u rainbowWithSha384;
    public static final u rainbowWithSha512;
    public static final u sphincs256;
    public static final u sphincs256_with_BLAKE512;
    public static final u sphincs256_with_SHA3_512;
    public static final u sphincs256_with_SHA512;
    public static final u xmss;
    public static final u xmss_SHA256;
    public static final u xmss_SHA256ph;
    public static final u xmss_SHA512;
    public static final u xmss_SHA512ph;
    public static final u xmss_SHAKE128;
    public static final u xmss_SHAKE128ph;
    public static final u xmss_SHAKE256;
    public static final u xmss_SHAKE256ph;
    public static final u xmss_mt;
    public static final u xmss_mt_SHA256;
    public static final u xmss_mt_SHA256ph;
    public static final u xmss_mt_SHA512;
    public static final u xmss_mt_SHA512ph;
    public static final u xmss_mt_SHAKE128;
    public static final u xmss_mt_SHAKE128ph;
    public static final u xmss_mt_SHAKE256;
    public static final u xmss_mt_SHAKE256ph;
    public static final u xmss_mt_with_SHA256;
    public static final u xmss_mt_with_SHA512;
    public static final u xmss_mt_with_SHAKE128;
    public static final u xmss_mt_with_SHAKE256;
    public static final u xmss_with_SHA256;
    public static final u xmss_with_SHA512;
    public static final u xmss_with_SHAKE128;
    public static final u xmss_with_SHAKE256;

    static {
        u uVar = new u("1.3.6.1.4.1.8301.3.1.3.5.3.2");
        rainbow = uVar;
        rainbowWithSha1 = uVar.w("1");
        rainbowWithSha224 = uVar.w(ExifInterface.GPS_MEASUREMENT_2D);
        rainbowWithSha256 = uVar.w(ExifInterface.GPS_MEASUREMENT_3D);
        rainbowWithSha384 = uVar.w("4");
        rainbowWithSha512 = uVar.w("5");
        u uVar2 = new u("1.3.6.1.4.1.8301.3.1.3.3");
        gmss = uVar2;
        gmssWithSha1 = uVar2.w("1");
        gmssWithSha224 = uVar2.w(ExifInterface.GPS_MEASUREMENT_2D);
        gmssWithSha256 = uVar2.w(ExifInterface.GPS_MEASUREMENT_3D);
        gmssWithSha384 = uVar2.w("4");
        gmssWithSha512 = uVar2.w("5");
        mcEliece = new u(n9.f.OID);
        mcElieceCca2 = new u(n9.e.OID);
        mcElieceFujisaki = new u("1.3.6.1.4.1.8301.3.1.3.4.2.1");
        mcEliecePointcheval = new u("1.3.6.1.4.1.8301.3.1.3.4.2.2");
        mcElieceKobara_Imai = new u("1.3.6.1.4.1.8301.3.1.3.4.2.3");
        sphincs256 = r8.a.sphincs256;
        sphincs256_with_BLAKE512 = r8.a.sphincs256_with_BLAKE512;
        sphincs256_with_SHA512 = r8.a.sphincs256_with_SHA512;
        sphincs256_with_SHA3_512 = r8.a.sphincs256_with_SHA3_512;
        newHope = r8.a.newHope;
        xmss = r8.a.xmss;
        u uVar3 = r8.a.xmss_SHA256ph;
        xmss_SHA256ph = uVar3;
        u uVar4 = r8.a.xmss_SHA512ph;
        xmss_SHA512ph = uVar4;
        u uVar5 = r8.a.xmss_SHAKE128ph;
        xmss_SHAKE128ph = uVar5;
        u uVar6 = r8.a.xmss_SHAKE256ph;
        xmss_SHAKE256ph = uVar6;
        xmss_SHA256 = r8.a.xmss_SHA256;
        xmss_SHA512 = r8.a.xmss_SHA512;
        xmss_SHAKE128 = r8.a.xmss_SHAKE128;
        xmss_SHAKE256 = r8.a.xmss_SHAKE256;
        xmss_mt = r8.a.xmss_mt;
        u uVar7 = r8.a.xmss_mt_SHA256ph;
        xmss_mt_SHA256ph = uVar7;
        u uVar8 = r8.a.xmss_mt_SHA512ph;
        xmss_mt_SHA512ph = uVar8;
        xmss_mt_SHAKE128ph = r8.a.xmss_mt_SHAKE128ph;
        xmss_mt_SHAKE256ph = r8.a.xmss_mt_SHAKE256ph;
        xmss_mt_SHA256 = r8.a.xmss_mt_SHA256;
        xmss_mt_SHA512 = r8.a.xmss_mt_SHA512;
        u uVar9 = r8.a.xmss_mt_SHAKE128;
        xmss_mt_SHAKE128 = uVar9;
        u uVar10 = r8.a.xmss_mt_SHAKE256;
        xmss_mt_SHAKE256 = uVar10;
        xmss_with_SHA256 = uVar3;
        xmss_with_SHA512 = uVar4;
        xmss_with_SHAKE128 = uVar5;
        xmss_with_SHAKE256 = uVar6;
        xmss_mt_with_SHA256 = uVar7;
        xmss_mt_with_SHA512 = uVar8;
        xmss_mt_with_SHAKE128 = uVar9;
        xmss_mt_with_SHAKE256 = uVar10;
        qTESLA = r8.a.qTESLA;
        qTESLA_p_I = r8.a.qTESLA_p_I;
        qTESLA_p_III = r8.a.qTESLA_p_III;
    }
}
