package oa;

import java.util.Locale;
import java.util.function.Supplier;

/* JADX INFO: loaded from: classes9.dex */
public final class q extends g {
    private final boolean autoGenerated;
    private final String code;
    private final x9.m format;
    private final Locale locale;

    public static final class a {
        private Boolean autoGenerated;
        private String content;
        private d deliveryMethod = d.PROGRESSIVE_HTTP;
        private String id;
        private boolean isUrl;
        private String languageCode;
        private String manifestUrl;
        private x9.m mediaFormat;

        public a c(String str, boolean z6) {
            this.content = str;
            this.isUrl = z6;
            return this;
        }

        public a d(String str) {
            this.languageCode = str;
            return this;
        }

        public a e(x9.m mVar) {
            this.mediaFormat = mVar;
            return this;
        }

        public q a() throws aa.h {
            String str;
            if (this.content == null) {
                throw new IllegalStateException("No valid content was specified. Please specify a valid one with setContent.");
            }
            if (this.deliveryMethod == null) {
                throw new IllegalStateException("The delivery method of the subtitles stream has been set as null, which is not allowed. Pass a valid one instead withsetDeliveryMethod.");
            }
            String str2 = this.languageCode;
            if (str2 == null) {
                throw new IllegalStateException("The language code of the subtitles stream has been not set or is null. Make sure you specified an non null language code with setLanguageCode.");
            }
            if (this.autoGenerated == null) {
                throw new IllegalStateException("The subtitles stream has been not set as an autogenerated subtitles stream or not. Please specify this information with setIsAutoGenerated.");
            }
            if (this.id == null) {
                x9.m mVar = this.mediaFormat;
                if (mVar != null) {
                    str = "." + mVar.suffix;
                } else {
                    str = "";
                }
                this.id = str2 + str;
            }
            return new q(this.id, this.content, this.isUrl, this.mediaFormat, this.deliveryMethod, this.languageCode, this.autoGenerated.booleanValue(), this.manifestUrl);
        }

        public a b(boolean z6) {
            this.autoGenerated = Boolean.valueOf(z6);
            return this;
        }
    }

    private q(String str, String str2, boolean z6, x9.m mVar, d dVar, final String str3, boolean z10, String str4) throws aa.h {
        super(str, str2, z6, mVar, dVar, str4);
        this.locale = (Locale) qa.f.a(str3).orElseThrow(new Supplier() { // from class: oa.p
            @Override // java.util.function.Supplier
            public final Object get() {
                return q.g(str3);
            }
        });
        this.code = str3;
        this.format = mVar;
        this.autoGenerated = z10;
    }

    /* JADX INFO: Access modifiers changed from: private */
    public static /* synthetic */ aa.h g(String str) {
        return new aa.h("not a valid locale language code: " + str);
    }

    @Override // oa.g
    public boolean b(g gVar) {
        if (super.b(gVar) && (gVar instanceof q)) {
            q qVar = (q) gVar;
            if (this.code.equals(qVar.code) && this.autoGenerated == qVar.autoGenerated) {
                return true;
            }
        }
        return false;
    }
}
