package r8;

import androidx.exifinterface.media.ExifInterface;
import org.bouncycastle.asn1.u;

/* JADX INFO: loaded from: classes6.dex */
public interface a {
    public static final u bc;
    public static final u bc_exch;
    public static final u bc_ext;
    public static final u bc_pbe;
    public static final u bc_pbe_sha1;
    public static final u bc_pbe_sha1_pkcs12;
    public static final u bc_pbe_sha1_pkcs12_aes128_cbc;
    public static final u bc_pbe_sha1_pkcs12_aes192_cbc;
    public static final u bc_pbe_sha1_pkcs12_aes256_cbc;
    public static final u bc_pbe_sha1_pkcs5;
    public static final u bc_pbe_sha224;
    public static final u bc_pbe_sha256;
    public static final u bc_pbe_sha256_pkcs12;
    public static final u bc_pbe_sha256_pkcs12_aes128_cbc;
    public static final u bc_pbe_sha256_pkcs12_aes192_cbc;
    public static final u bc_pbe_sha256_pkcs12_aes256_cbc;
    public static final u bc_pbe_sha256_pkcs5;
    public static final u bc_pbe_sha384;
    public static final u bc_pbe_sha512;
    public static final u bc_sig;
    public static final u linkedCertificate;
    public static final u newHope;
    public static final u qTESLA;
    public static final u qTESLA_Rnd1_I;
    public static final u qTESLA_Rnd1_III_size;
    public static final u qTESLA_Rnd1_III_speed;
    public static final u qTESLA_Rnd1_p_I;
    public static final u qTESLA_Rnd1_p_III;
    public static final u qTESLA_p_I;
    public static final u qTESLA_p_III;
    public static final u sphincs256;
    public static final u sphincs256_with_BLAKE512;
    public static final u sphincs256_with_SHA3_512;
    public static final u sphincs256_with_SHA512;
    public static final u xmss;
    public static final u xmss_SHA256;
    public static final u xmss_SHA256ph;
    public static final u xmss_SHA512;
    public static final u xmss_SHA512ph;
    public static final u xmss_SHAKE128;
    public static final u xmss_SHAKE128ph;
    public static final u xmss_SHAKE256;
    public static final u xmss_SHAKE256ph;
    public static final u xmss_mt;
    public static final u xmss_mt_SHA256;
    public static final u xmss_mt_SHA256ph;
    public static final u xmss_mt_SHA512;
    public static final u xmss_mt_SHA512ph;
    public static final u xmss_mt_SHAKE128;
    public static final u xmss_mt_SHAKE128ph;
    public static final u xmss_mt_SHAKE256;
    public static final u xmss_mt_SHAKE256ph;
    public static final u xmss_mt_with_SHA256;
    public static final u xmss_mt_with_SHA512;
    public static final u xmss_mt_with_SHAKE128;
    public static final u xmss_mt_with_SHAKE256;
    public static final u xmss_with_SHA256;
    public static final u xmss_with_SHA512;
    public static final u xmss_with_SHAKE128;
    public static final u xmss_with_SHAKE256;

    static {
        u uVar = new u("1.3.6.1.4.1.22554");
        bc = uVar;
        u uVarW = uVar.w("1");
        bc_pbe = uVarW;
        u uVarW2 = uVarW.w("1");
        bc_pbe_sha1 = uVarW2;
        u uVarW3 = uVarW.w("2.1");
        bc_pbe_sha256 = uVarW3;
        bc_pbe_sha384 = uVarW.w("2.2");
        bc_pbe_sha512 = uVarW.w("2.3");
        bc_pbe_sha224 = uVarW.w("2.4");
        bc_pbe_sha1_pkcs5 = uVarW2.w("1");
        u uVarW4 = uVarW2.w(ExifInterface.GPS_MEASUREMENT_2D);
        bc_pbe_sha1_pkcs12 = uVarW4;
        bc_pbe_sha256_pkcs5 = uVarW3.w("1");
        u uVarW5 = uVarW3.w(ExifInterface.GPS_MEASUREMENT_2D);
        bc_pbe_sha256_pkcs12 = uVarW5;
        bc_pbe_sha1_pkcs12_aes128_cbc = uVarW4.w("1.2");
        bc_pbe_sha1_pkcs12_aes192_cbc = uVarW4.w("1.22");
        bc_pbe_sha1_pkcs12_aes256_cbc = uVarW4.w("1.42");
        bc_pbe_sha256_pkcs12_aes128_cbc = uVarW5.w("1.2");
        bc_pbe_sha256_pkcs12_aes192_cbc = uVarW5.w("1.22");
        bc_pbe_sha256_pkcs12_aes256_cbc = uVarW5.w("1.42");
        u uVarW6 = uVar.w(ExifInterface.GPS_MEASUREMENT_2D);
        bc_sig = uVarW6;
        u uVarW7 = uVarW6.w("1");
        sphincs256 = uVarW7;
        sphincs256_with_BLAKE512 = uVarW7.w("1");
        sphincs256_with_SHA512 = uVarW7.w(ExifInterface.GPS_MEASUREMENT_2D);
        sphincs256_with_SHA3_512 = uVarW7.w(ExifInterface.GPS_MEASUREMENT_3D);
        u uVarW8 = uVarW6.w(ExifInterface.GPS_MEASUREMENT_2D);
        xmss = uVarW8;
        u uVarW9 = uVarW8.w("1");
        xmss_SHA256ph = uVarW9;
        u uVarW10 = uVarW8.w(ExifInterface.GPS_MEASUREMENT_2D);
        xmss_SHA512ph = uVarW10;
        u uVarW11 = uVarW8.w(ExifInterface.GPS_MEASUREMENT_3D);
        xmss_SHAKE128ph = uVarW11;
        u uVarW12 = uVarW8.w("4");
        xmss_SHAKE256ph = uVarW12;
        xmss_SHA256 = uVarW8.w("5");
        xmss_SHA512 = uVarW8.w("6");
        xmss_SHAKE128 = uVarW8.w("7");
        xmss_SHAKE256 = uVarW8.w("8");
        u uVarW13 = uVarW6.w(ExifInterface.GPS_MEASUREMENT_3D);
        xmss_mt = uVarW13;
        u uVarW14 = uVarW13.w("1");
        xmss_mt_SHA256ph = uVarW14;
        u uVarW15 = uVarW13.w(ExifInterface.GPS_MEASUREMENT_2D);
        xmss_mt_SHA512ph = uVarW15;
        xmss_mt_SHAKE128ph = uVarW13.w(ExifInterface.GPS_MEASUREMENT_3D);
        xmss_mt_SHAKE256ph = uVarW13.w("4");
        xmss_mt_SHA256 = uVarW13.w("5");
        xmss_mt_SHA512 = uVarW13.w("6");
        u uVarW16 = uVarW13.w("7");
        xmss_mt_SHAKE128 = uVarW16;
        u uVarW17 = uVarW13.w("8");
        xmss_mt_SHAKE256 = uVarW17;
        xmss_with_SHA256 = uVarW9;
        xmss_with_SHA512 = uVarW10;
        xmss_with_SHAKE128 = uVarW11;
        xmss_with_SHAKE256 = uVarW12;
        xmss_mt_with_SHA256 = uVarW14;
        xmss_mt_with_SHA512 = uVarW15;
        xmss_mt_with_SHAKE128 = uVarW16;
        xmss_mt_with_SHAKE256 = uVarW17;
        u uVarW18 = uVarW6.w("4");
        qTESLA = uVarW18;
        qTESLA_Rnd1_I = uVarW18.w("1");
        qTESLA_Rnd1_III_size = uVarW18.w(ExifInterface.GPS_MEASUREMENT_2D);
        qTESLA_Rnd1_III_speed = uVarW18.w(ExifInterface.GPS_MEASUREMENT_3D);
        qTESLA_Rnd1_p_I = uVarW18.w("4");
        qTESLA_Rnd1_p_III = uVarW18.w("5");
        qTESLA_p_I = uVarW18.w("11");
        qTESLA_p_III = uVarW18.w("12");
        u uVarW19 = uVar.w(ExifInterface.GPS_MEASUREMENT_3D);
        bc_exch = uVarW19;
        newHope = uVarW19.w("1");
        u uVarW20 = uVar.w("4");
        bc_ext = uVarW20;
        linkedCertificate = uVarW20.w("1");
    }
}
