package t8;

import androidx.exifinterface.media.ExifInterface;
import androidx.room.RoomMasterTable;
import org.bouncycastle.asn1.u;

/* JADX INFO: loaded from: classes10.dex */
public interface a {
    public static final u aes;
    public static final u dsa_with_sha224;
    public static final u dsa_with_sha256;
    public static final u dsa_with_sha384;
    public static final u dsa_with_sha512;
    public static final u hashAlgs;
    public static final u id_KmacWithSHAKE128;
    public static final u id_KmacWithSHAKE256;
    public static final u id_aes128_CBC;
    public static final u id_aes128_CCM;
    public static final u id_aes128_CFB;
    public static final u id_aes128_ECB;
    public static final u id_aes128_GCM;
    public static final u id_aes128_OFB;
    public static final u id_aes128_wrap;
    public static final u id_aes128_wrap_pad;
    public static final u id_aes192_CBC;
    public static final u id_aes192_CCM;
    public static final u id_aes192_CFB;
    public static final u id_aes192_ECB;
    public static final u id_aes192_GCM;
    public static final u id_aes192_OFB;
    public static final u id_aes192_wrap;
    public static final u id_aes192_wrap_pad;
    public static final u id_aes256_CBC;
    public static final u id_aes256_CCM;
    public static final u id_aes256_CFB;
    public static final u id_aes256_ECB;
    public static final u id_aes256_GCM;
    public static final u id_aes256_OFB;
    public static final u id_aes256_wrap;
    public static final u id_aes256_wrap_pad;
    public static final u id_dsa_with_sha2;
    public static final u id_dsa_with_sha3_224;
    public static final u id_dsa_with_sha3_256;
    public static final u id_dsa_with_sha3_384;
    public static final u id_dsa_with_sha3_512;
    public static final u id_ecdsa_with_sha3_224;
    public static final u id_ecdsa_with_sha3_256;
    public static final u id_ecdsa_with_sha3_384;
    public static final u id_ecdsa_with_sha3_512;
    public static final u id_hmacWithSHA3_224;
    public static final u id_hmacWithSHA3_256;
    public static final u id_hmacWithSHA3_384;
    public static final u id_hmacWithSHA3_512;
    public static final u id_rsassa_pkcs1_v1_5_with_sha3_224;
    public static final u id_rsassa_pkcs1_v1_5_with_sha3_256;
    public static final u id_rsassa_pkcs1_v1_5_with_sha3_384;
    public static final u id_rsassa_pkcs1_v1_5_with_sha3_512;
    public static final u id_sha224;
    public static final u id_sha256;
    public static final u id_sha384;
    public static final u id_sha3_224;
    public static final u id_sha3_256;
    public static final u id_sha3_384;
    public static final u id_sha3_512;
    public static final u id_sha512;
    public static final u id_sha512_224;
    public static final u id_sha512_256;
    public static final u id_shake128;
    public static final u id_shake128_len;
    public static final u id_shake256;
    public static final u id_shake256_len;
    public static final u nistAlgorithm;
    public static final u sigAlgs;

    static {
        u uVar = new u("2.16.840.1.101.3.4");
        nistAlgorithm = uVar;
        u uVarW = uVar.w(ExifInterface.GPS_MEASUREMENT_2D);
        hashAlgs = uVarW;
        id_sha256 = uVarW.w("1");
        id_sha384 = uVarW.w(ExifInterface.GPS_MEASUREMENT_2D);
        id_sha512 = uVarW.w(ExifInterface.GPS_MEASUREMENT_3D);
        id_sha224 = uVarW.w("4");
        id_sha512_224 = uVarW.w("5");
        id_sha512_256 = uVarW.w("6");
        id_sha3_224 = uVarW.w("7");
        id_sha3_256 = uVarW.w("8");
        id_sha3_384 = uVarW.w("9");
        id_sha3_512 = uVarW.w("10");
        id_shake128 = uVarW.w("11");
        id_shake256 = uVarW.w("12");
        id_hmacWithSHA3_224 = uVarW.w("13");
        id_hmacWithSHA3_256 = uVarW.w("14");
        id_hmacWithSHA3_384 = uVarW.w("15");
        id_hmacWithSHA3_512 = uVarW.w("16");
        id_shake128_len = uVarW.w("17");
        id_shake256_len = uVarW.w("18");
        id_KmacWithSHAKE128 = uVarW.w("19");
        id_KmacWithSHAKE256 = uVarW.w("20");
        u uVarW2 = uVar.w("1");
        aes = uVarW2;
        id_aes128_ECB = uVarW2.w("1");
        id_aes128_CBC = uVarW2.w(ExifInterface.GPS_MEASUREMENT_2D);
        id_aes128_OFB = uVarW2.w(ExifInterface.GPS_MEASUREMENT_3D);
        id_aes128_CFB = uVarW2.w("4");
        id_aes128_wrap = uVarW2.w("5");
        id_aes128_GCM = uVarW2.w("6");
        id_aes128_CCM = uVarW2.w("7");
        id_aes128_wrap_pad = uVarW2.w("8");
        id_aes192_ECB = uVarW2.w("21");
        id_aes192_CBC = uVarW2.w("22");
        id_aes192_OFB = uVarW2.w("23");
        id_aes192_CFB = uVarW2.w("24");
        id_aes192_wrap = uVarW2.w("25");
        id_aes192_GCM = uVarW2.w("26");
        id_aes192_CCM = uVarW2.w("27");
        id_aes192_wrap_pad = uVarW2.w("28");
        id_aes256_ECB = uVarW2.w("41");
        id_aes256_CBC = uVarW2.w(RoomMasterTable.DEFAULT_ID);
        id_aes256_OFB = uVarW2.w("43");
        id_aes256_CFB = uVarW2.w("44");
        id_aes256_wrap = uVarW2.w("45");
        id_aes256_GCM = uVarW2.w("46");
        id_aes256_CCM = uVarW2.w("47");
        id_aes256_wrap_pad = uVarW2.w("48");
        u uVarW3 = uVar.w(ExifInterface.GPS_MEASUREMENT_3D);
        sigAlgs = uVarW3;
        id_dsa_with_sha2 = uVarW3;
        dsa_with_sha224 = uVarW3.w("1");
        dsa_with_sha256 = uVarW3.w(ExifInterface.GPS_MEASUREMENT_2D);
        dsa_with_sha384 = uVarW3.w(ExifInterface.GPS_MEASUREMENT_3D);
        dsa_with_sha512 = uVarW3.w("4");
        id_dsa_with_sha3_224 = uVarW3.w("5");
        id_dsa_with_sha3_256 = uVarW3.w("6");
        id_dsa_with_sha3_384 = uVarW3.w("7");
        id_dsa_with_sha3_512 = uVarW3.w("8");
        id_ecdsa_with_sha3_224 = uVarW3.w("9");
        id_ecdsa_with_sha3_256 = uVarW3.w("10");
        id_ecdsa_with_sha3_384 = uVarW3.w("11");
        id_ecdsa_with_sha3_512 = uVarW3.w("12");
        id_rsassa_pkcs1_v1_5_with_sha3_224 = uVarW3.w("13");
        id_rsassa_pkcs1_v1_5_with_sha3_256 = uVarW3.w("14");
        id_rsassa_pkcs1_v1_5_with_sha3_384 = uVarW3.w("15");
        id_rsassa_pkcs1_v1_5_with_sha3_512 = uVarW3.w("16");
    }
}
