package com.mobeta.android.dslv;

import android.R;

/* JADX INFO: loaded from: classes11.dex */
public final class d {
    public static final int ColorStateListItem_alpha = 3;
    public static final int ColorStateListItem_android_alpha = 1;
    public static final int ColorStateListItem_android_color = 0;
    public static final int ColorStateListItem_android_lStar = 2;
    public static final int ColorStateListItem_lStar = 4;
    public static final int CoordinatorLayout_Layout_android_layout_gravity = 0;
    public static final int CoordinatorLayout_Layout_layout_anchor = 1;
    public static final int CoordinatorLayout_Layout_layout_anchorGravity = 2;
    public static final int CoordinatorLayout_Layout_layout_behavior = 3;
    public static final int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 4;
    public static final int CoordinatorLayout_Layout_layout_insetEdge = 5;
    public static final int CoordinatorLayout_Layout_layout_keyline = 6;
    public static final int CoordinatorLayout_keylines = 0;
    public static final int CoordinatorLayout_statusBarBackground = 1;
    public static final int DragSortListView_click_remove_id = 0;
    public static final int DragSortListView_collapsed_height = 1;
    public static final int DragSortListView_drag_enabled = 2;
    public static final int DragSortListView_drag_handle_id = 3;
    public static final int DragSortListView_drag_scroll_start = 4;
    public static final int DragSortListView_drag_start_mode = 5;
    public static final int DragSortListView_drop_animation_duration = 6;
    public static final int DragSortListView_fling_handle_id = 7;
    public static final int DragSortListView_float_alpha = 8;
    public static final int DragSortListView_float_background_color = 9;
    public static final int DragSortListView_max_drag_scroll_speed = 10;
    public static final int DragSortListView_remove_animation_duration = 11;
    public static final int DragSortListView_remove_enabled = 12;
    public static final int DragSortListView_remove_mode = 13;
    public static final int DragSortListView_slide_shuffle_speed = 14;
    public static final int DragSortListView_sort_enabled = 15;
    public static final int DragSortListView_track_drag_sort = 16;
    public static final int DragSortListView_use_default_controller = 17;
    public static final int FontFamilyFont_android_font = 0;
    public static final int FontFamilyFont_android_fontStyle = 2;
    public static final int FontFamilyFont_android_fontVariationSettings = 4;
    public static final int FontFamilyFont_android_fontWeight = 1;
    public static final int FontFamilyFont_android_ttcIndex = 3;
    public static final int FontFamilyFont_font = 5;
    public static final int FontFamilyFont_fontStyle = 6;
    public static final int FontFamilyFont_fontVariationSettings = 7;
    public static final int FontFamilyFont_fontWeight = 8;
    public static final int FontFamilyFont_ttcIndex = 9;
    public static final int FontFamily_fontProviderAuthority = 0;
    public static final int FontFamily_fontProviderCerts = 1;
    public static final int FontFamily_fontProviderFetchStrategy = 2;
    public static final int FontFamily_fontProviderFetchTimeout = 3;
    public static final int FontFamily_fontProviderPackage = 4;
    public static final int FontFamily_fontProviderQuery = 5;
    public static final int FontFamily_fontProviderSystemFontFamily = 6;
    public static final int GradientColorItem_android_color = 0;
    public static final int GradientColorItem_android_offset = 1;
    public static final int GradientColor_android_centerColor = 7;
    public static final int GradientColor_android_centerX = 3;
    public static final int GradientColor_android_centerY = 4;
    public static final int GradientColor_android_endColor = 1;
    public static final int GradientColor_android_endX = 10;
    public static final int GradientColor_android_endY = 11;
    public static final int GradientColor_android_gradientRadius = 5;
    public static final int GradientColor_android_startColor = 0;
    public static final int GradientColor_android_startX = 8;
    public static final int GradientColor_android_startY = 9;
    public static final int GradientColor_android_tileMode = 6;
    public static final int GradientColor_android_type = 2;
    public static final int[] ColorStateListItem = {R.attr.color, R.attr.alpha, R.attr.lStar, com.narvii.amino.master.R.attr.alpha, com.narvii.amino.master.R.attr.lStar};
    public static final int[] CoordinatorLayout = {com.narvii.amino.master.R.attr.keylines, com.narvii.amino.master.R.attr.statusBarBackground};
    public static final int[] CoordinatorLayout_Layout = {R.attr.layout_gravity, com.narvii.amino.master.R.attr.layout_anchor, com.narvii.amino.master.R.attr.layout_anchorGravity, com.narvii.amino.master.R.attr.layout_behavior, com.narvii.amino.master.R.attr.layout_dodgeInsetEdges, com.narvii.amino.master.R.attr.layout_insetEdge, com.narvii.amino.master.R.attr.layout_keyline};
    public static final int[] DragSortListView = {com.narvii.amino.master.R.attr.click_remove_id, com.narvii.amino.master.R.attr.collapsed_height, com.narvii.amino.master.R.attr.drag_enabled, com.narvii.amino.master.R.attr.drag_handle_id, com.narvii.amino.master.R.attr.drag_scroll_start, com.narvii.amino.master.R.attr.drag_start_mode, com.narvii.amino.master.R.attr.drop_animation_duration, com.narvii.amino.master.R.attr.fling_handle_id, com.narvii.amino.master.R.attr.float_alpha, com.narvii.amino.master.R.attr.float_background_color, com.narvii.amino.master.R.attr.max_drag_scroll_speed, com.narvii.amino.master.R.attr.remove_animation_duration, com.narvii.amino.master.R.attr.remove_enabled, com.narvii.amino.master.R.attr.remove_mode, com.narvii.amino.master.R.attr.slide_shuffle_speed, com.narvii.amino.master.R.attr.sort_enabled, com.narvii.amino.master.R.attr.track_drag_sort, com.narvii.amino.master.R.attr.use_default_controller};
    public static final int[] FontFamily = {com.narvii.amino.master.R.attr.fontProviderAuthority, com.narvii.amino.master.R.attr.fontProviderCerts, com.narvii.amino.master.R.attr.fontProviderFetchStrategy, com.narvii.amino.master.R.attr.fontProviderFetchTimeout, com.narvii.amino.master.R.attr.fontProviderPackage, com.narvii.amino.master.R.attr.fontProviderQuery, com.narvii.amino.master.R.attr.fontProviderSystemFontFamily};
    public static final int[] FontFamilyFont = {R.attr.font, R.attr.fontWeight, R.attr.fontStyle, R.attr.ttcIndex, R.attr.fontVariationSettings, com.narvii.amino.master.R.attr.font, com.narvii.amino.master.R.attr.fontStyle, com.narvii.amino.master.R.attr.fontVariationSettings, com.narvii.amino.master.R.attr.fontWeight, com.narvii.amino.master.R.attr.ttcIndex};
    public static final int[] GradientColor = {R.attr.startColor, R.attr.endColor, R.attr.type, R.attr.centerX, R.attr.centerY, R.attr.gradientRadius, R.attr.tileMode, R.attr.centerColor, R.attr.startX, R.attr.startY, R.attr.endX, R.attr.endY};
    public static final int[] GradientColorItem = {R.attr.color, R.attr.offset};
}
