package com.android.billingclient.api;

/* JADX INFO: loaded from: classes7.dex */
final class p0 {
    static final h zzA;
    static final h zzB;
    static final h zzC;
    static final h zzD;
    static final h zzE;
    public static final /* synthetic */ int zzF = 0;
    static final h zza;
    static final h zzb;
    static final h zzc;
    static final h zzd;
    static final h zze;
    static final h zzf;
    static final h zzg;
    static final h zzh;
    static final h zzi;
    static final h zzj;
    static final h zzk;
    static final h zzl;
    static final h zzm;
    static final h zzn;
    static final h zzo;
    static final h zzp;
    static final h zzq;
    static final h zzr;
    static final h zzs;
    static final h zzt;
    static final h zzu;
    static final h zzv;
    static final h zzw;
    static final h zzx;
    static final h zzy;
    static final h zzz;

    static {
        h.a aVarC = h.c();
        aVarC.c(3);
        aVarC.b("Google Play In-app Billing API version is less than 3");
        zza = aVarC.a();
        h.a aVarC2 = h.c();
        aVarC2.c(3);
        aVarC2.b("Google Play In-app Billing API version is less than 9");
        zzb = aVarC2.a();
        h.a aVarC3 = h.c();
        aVarC3.c(3);
        aVarC3.b("Billing service unavailable on device.");
        zzc = aVarC3.a();
        h.a aVarC4 = h.c();
        aVarC4.c(5);
        aVarC4.b("Client is already in the process of connecting to billing service.");
        zzd = aVarC4.a();
        h.a aVarC5 = h.c();
        aVarC5.c(5);
        aVarC5.b("The list of SKUs can't be empty.");
        zze = aVarC5.a();
        h.a aVarC6 = h.c();
        aVarC6.c(5);
        aVarC6.b("SKU type can't be empty.");
        zzf = aVarC6.a();
        h.a aVarC7 = h.c();
        aVarC7.c(5);
        aVarC7.b("Product type can't be empty.");
        zzg = aVarC7.a();
        h.a aVarC8 = h.c();
        aVarC8.c(-2);
        aVarC8.b("Client does not support extra params.");
        zzh = aVarC8.a();
        h.a aVarC9 = h.c();
        aVarC9.c(5);
        aVarC9.b("Invalid purchase token.");
        zzi = aVarC9.a();
        h.a aVarC10 = h.c();
        aVarC10.c(6);
        aVarC10.b("An internal error occurred.");
        zzj = aVarC10.a();
        h.a aVarC11 = h.c();
        aVarC11.c(5);
        aVarC11.b("SKU can't be null.");
        zzk = aVarC11.a();
        h.a aVarC12 = h.c();
        aVarC12.c(0);
        zzl = aVarC12.a();
        h.a aVarC13 = h.c();
        aVarC13.c(-1);
        aVarC13.b("Service connection is disconnected.");
        zzm = aVarC13.a();
        h.a aVarC14 = h.c();
        aVarC14.c(2);
        aVarC14.b("Timeout communicating with service.");
        zzn = aVarC14.a();
        h.a aVarC15 = h.c();
        aVarC15.c(-2);
        aVarC15.b("Client does not support subscriptions.");
        zzo = aVarC15.a();
        h.a aVarC16 = h.c();
        aVarC16.c(-2);
        aVarC16.b("Client does not support subscriptions update.");
        zzp = aVarC16.a();
        h.a aVarC17 = h.c();
        aVarC17.c(-2);
        aVarC17.b("Client does not support get purchase history.");
        zzq = aVarC17.a();
        h.a aVarC18 = h.c();
        aVarC18.c(-2);
        aVarC18.b("Client does not support price change confirmation.");
        zzr = aVarC18.a();
        h.a aVarC19 = h.c();
        aVarC19.c(-2);
        aVarC19.b("Play Store version installed does not support cross selling products.");
        zzs = aVarC19.a();
        h.a aVarC20 = h.c();
        aVarC20.c(-2);
        aVarC20.b("Client does not support multi-item purchases.");
        zzt = aVarC20.a();
        h.a aVarC21 = h.c();
        aVarC21.c(-2);
        aVarC21.b("Client does not support offer_id_token.");
        zzu = aVarC21.a();
        h.a aVarC22 = h.c();
        aVarC22.c(-2);
        aVarC22.b("Client does not support ProductDetails.");
        zzv = aVarC22.a();
        h.a aVarC23 = h.c();
        aVarC23.c(-2);
        aVarC23.b("Client does not support in-app messages.");
        zzw = aVarC23.a();
        h.a aVarC24 = h.c();
        aVarC24.c(-2);
        aVarC24.b("Client does not support user choice billing.");
        zzx = aVarC24.a();
        h.a aVarC25 = h.c();
        aVarC25.c(5);
        aVarC25.b("Unknown feature");
        zzy = aVarC25.a();
        h.a aVarC26 = h.c();
        aVarC26.c(-2);
        aVarC26.b("Play Store version installed does not support get billing config.");
        zzz = aVarC26.a();
        h.a aVarC27 = h.c();
        aVarC27.c(-2);
        aVarC27.b("Query product details with serialized docid is not supported.");
        zzA = aVarC27.a();
        h.a aVarC28 = h.c();
        aVarC28.c(4);
        aVarC28.b("Item is unavailable for purchase.");
        zzB = aVarC28.a();
        h.a aVarC29 = h.c();
        aVarC29.c(-2);
        aVarC29.b("Query product details with developer specified account is not supported.");
        zzC = aVarC29.a();
        h.a aVarC30 = h.c();
        aVarC30.c(-2);
        aVarC30.b("Play Store version installed does not support alternative billing only.");
        zzD = aVarC30.a();
        h.a aVarC31 = h.c();
        aVarC31.c(5);
        aVarC31.b("To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.");
        zzE = aVarC31.a();
    }

    static h a(int i10, String str) {
        h.a aVarC = h.c();
        aVarC.c(i10);
        aVarC.b(str);
        return aVarC.a();
    }
}
