package v8;

import androidx.exifinterface.media.ExifInterface;
import org.bouncycastle.asn1.u;

/* JADX INFO: loaded from: classes11.dex */
public interface a {
    public static final u RC2_CBC;
    public static final u bagtypes;
    public static final u canNotDecryptAny;
    public static final u certBag;
    public static final u certTypes;
    public static final u crlBag;
    public static final u crlTypes;
    public static final u data;
    public static final u des_EDE3_CBC;
    public static final u dhKeyAgreement;
    public static final u digestAlgorithm;
    public static final u digestedData;
    public static final u encryptedData;
    public static final u encryptionAlgorithm;
    public static final u envelopedData;
    public static final u id_PBES2;
    public static final u id_PBKDF2;
    public static final u id_RSAES_OAEP;
    public static final u id_RSASSA_PSS;
    public static final u id_aa;
    public static final u id_aa_asymmDecryptKeyID;
    public static final u id_aa_cmsAlgorithmProtect;
    public static final u id_aa_commitmentType;
    public static final u id_aa_communityIdentifiers;
    public static final u id_aa_contentHint;
    public static final u id_aa_contentIdentifier;
    public static final u id_aa_contentReference;
    public static final u id_aa_decryptKeyID;
    public static final u id_aa_encrypKeyPref;
    public static final u id_aa_ets_archiveTimestamp;
    public static final u id_aa_ets_certCRLTimestamp;
    public static final u id_aa_ets_certValues;
    public static final u id_aa_ets_certificateRefs;
    public static final u id_aa_ets_commitmentType;
    public static final u id_aa_ets_contentTimestamp;
    public static final u id_aa_ets_escTimeStamp;
    public static final u id_aa_ets_otherSigCert;
    public static final u id_aa_ets_revocationRefs;
    public static final u id_aa_ets_revocationValues;
    public static final u id_aa_ets_sigPolicyId;
    public static final u id_aa_ets_signerAttr;
    public static final u id_aa_ets_signerLocation;
    public static final u id_aa_implCompressAlgs;
    public static final u id_aa_implCryptoAlgs;
    public static final u id_aa_msgSigDigest;
    public static final u id_aa_otherSigCert;
    public static final u id_aa_receiptRequest;
    public static final u id_aa_sigPolicyId;
    public static final u id_aa_signatureTimeStampToken;
    public static final u id_aa_signerLocation;
    public static final u id_aa_signingCertificate;
    public static final u id_aa_signingCertificateV2;
    public static final u id_alg;
    public static final u id_alg_AEADChaCha20Poly1305;
    public static final u id_alg_CMS3DESwrap;
    public static final u id_alg_CMSRC2wrap;
    public static final u id_alg_ESDH;
    public static final u id_alg_PWRI_KEK;
    public static final u id_alg_SSDH;
    public static final u id_alg_hkdf_with_sha256;
    public static final u id_alg_hkdf_with_sha384;
    public static final u id_alg_hkdf_with_sha512;
    public static final u id_alg_hss_lms_hashsig;
    public static final u id_ct;
    public static final u id_ct_TSTInfo;
    public static final u id_ct_authData;
    public static final u id_ct_authEnvelopedData;
    public static final u id_ct_compressedData;
    public static final u id_ct_timestampedData;
    public static final u id_cti;
    public static final u id_cti_ets_proofOfApproval;
    public static final u id_cti_ets_proofOfCreation;
    public static final u id_cti_ets_proofOfDelivery;
    public static final u id_cti_ets_proofOfOrigin;
    public static final u id_cti_ets_proofOfReceipt;
    public static final u id_cti_ets_proofOfSender;
    public static final u id_hmacWithSHA1;
    public static final u id_hmacWithSHA224;
    public static final u id_hmacWithSHA256;
    public static final u id_hmacWithSHA384;
    public static final u id_hmacWithSHA512;
    public static final u id_hmacWithSHA512_224;
    public static final u id_hmacWithSHA512_256;
    public static final u id_mgf1;
    public static final u id_pSpecified;
    public static final u id_rsa_KEM;
    public static final u id_smime;
    public static final String id_spq = "1.2.840.113549.1.9.16.5";
    public static final u id_spq_ets_unotice;
    public static final u id_spq_ets_uri;
    public static final u keyBag;
    public static final u md2;
    public static final u md2WithRSAEncryption;
    public static final u md4;
    public static final u md4WithRSAEncryption;
    public static final u md5;
    public static final u md5WithRSAEncryption;
    public static final u pbeWithMD2AndDES_CBC;
    public static final u pbeWithMD2AndRC2_CBC;
    public static final u pbeWithMD5AndDES_CBC;
    public static final u pbeWithMD5AndRC2_CBC;
    public static final u pbeWithSHA1AndDES_CBC;
    public static final u pbeWithSHA1AndRC2_CBC;
    public static final u pbeWithSHAAnd128BitRC2_CBC;
    public static final u pbeWithSHAAnd128BitRC4;
    public static final u pbeWithSHAAnd2_KeyTripleDES_CBC;
    public static final u pbeWithSHAAnd3_KeyTripleDES_CBC;
    public static final u pbeWithSHAAnd40BitRC2_CBC;
    public static final u pbeWithSHAAnd40BitRC4;
    public static final u pbewithSHAAnd40BitRC2_CBC;
    public static final u pkcs8ShroudedKeyBag;
    public static final u pkcs_1;
    public static final u pkcs_12;
    public static final u pkcs_12PbeIds;
    public static final u pkcs_3;
    public static final u pkcs_5;
    public static final u pkcs_7;
    public static final u pkcs_9;
    public static final u pkcs_9_at_binarySigningTime;
    public static final u pkcs_9_at_challengePassword;
    public static final u pkcs_9_at_contentType;
    public static final u pkcs_9_at_counterSignature;
    public static final u pkcs_9_at_emailAddress;
    public static final u pkcs_9_at_extendedCertificateAttributes;
    public static final u pkcs_9_at_extensionRequest;
    public static final u pkcs_9_at_friendlyName;
    public static final u pkcs_9_at_localKeyId;
    public static final u pkcs_9_at_messageDigest;
    public static final u pkcs_9_at_signingDescription;
    public static final u pkcs_9_at_signingTime;
    public static final u pkcs_9_at_smimeCapabilities;
    public static final u pkcs_9_at_unstructuredAddress;
    public static final u pkcs_9_at_unstructuredName;
    public static final u preferSignedData;
    public static final u rc4;
    public static final u rsaEncryption;
    public static final u sMIMECapabilitiesVersions;
    public static final u safeContentsBag;
    public static final u sdsiCertificate;
    public static final u secretBag;
    public static final u sha1WithRSAEncryption;
    public static final u sha224WithRSAEncryption;
    public static final u sha256WithRSAEncryption;
    public static final u sha384WithRSAEncryption;
    public static final u sha512WithRSAEncryption;
    public static final u sha512_224WithRSAEncryption;
    public static final u sha512_256WithRSAEncryption;
    public static final u signedAndEnvelopedData;
    public static final u signedData;
    public static final u srsaOAEPEncryptionSET;
    public static final u x509Certificate;
    public static final u x509Crl;
    public static final u x509certType;

    static {
        u uVar = new u("1.2.840.113549.1.1");
        pkcs_1 = uVar;
        rsaEncryption = uVar.w("1");
        md2WithRSAEncryption = uVar.w(ExifInterface.GPS_MEASUREMENT_2D);
        md4WithRSAEncryption = uVar.w(ExifInterface.GPS_MEASUREMENT_3D);
        md5WithRSAEncryption = uVar.w("4");
        sha1WithRSAEncryption = uVar.w("5");
        srsaOAEPEncryptionSET = uVar.w("6");
        id_RSAES_OAEP = uVar.w("7");
        id_mgf1 = uVar.w("8");
        id_pSpecified = uVar.w("9");
        id_RSASSA_PSS = uVar.w("10");
        sha256WithRSAEncryption = uVar.w("11");
        sha384WithRSAEncryption = uVar.w("12");
        sha512WithRSAEncryption = uVar.w("13");
        sha224WithRSAEncryption = uVar.w("14");
        sha512_224WithRSAEncryption = uVar.w("15");
        sha512_256WithRSAEncryption = uVar.w("16");
        u uVar2 = new u("1.2.840.113549.1.3");
        pkcs_3 = uVar2;
        dhKeyAgreement = uVar2.w("1");
        u uVar3 = new u("1.2.840.113549.1.5");
        pkcs_5 = uVar3;
        pbeWithMD2AndDES_CBC = uVar3.w("1");
        pbeWithMD2AndRC2_CBC = uVar3.w("4");
        pbeWithMD5AndDES_CBC = uVar3.w(ExifInterface.GPS_MEASUREMENT_3D);
        pbeWithMD5AndRC2_CBC = uVar3.w("6");
        pbeWithSHA1AndDES_CBC = uVar3.w("10");
        pbeWithSHA1AndRC2_CBC = uVar3.w("11");
        id_PBES2 = uVar3.w("13");
        id_PBKDF2 = uVar3.w("12");
        u uVar4 = new u("1.2.840.113549.3");
        encryptionAlgorithm = uVar4;
        des_EDE3_CBC = uVar4.w("7");
        RC2_CBC = uVar4.w(ExifInterface.GPS_MEASUREMENT_2D);
        rc4 = uVar4.w("4");
        u uVar5 = new u("1.2.840.113549.2");
        digestAlgorithm = uVar5;
        md2 = uVar5.w(ExifInterface.GPS_MEASUREMENT_2D);
        md4 = uVar5.w("4");
        md5 = uVar5.w("5");
        id_hmacWithSHA1 = uVar5.w("7").C();
        id_hmacWithSHA224 = uVar5.w("8").C();
        id_hmacWithSHA256 = uVar5.w("9").C();
        id_hmacWithSHA384 = uVar5.w("10").C();
        id_hmacWithSHA512 = uVar5.w("11").C();
        id_hmacWithSHA512_224 = uVar5.w("12").C();
        id_hmacWithSHA512_256 = uVar5.w("13").C();
        pkcs_7 = new u("1.2.840.113549.1.7").C();
        data = new u("1.2.840.113549.1.7.1").C();
        signedData = new u("1.2.840.113549.1.7.2").C();
        envelopedData = new u("1.2.840.113549.1.7.3").C();
        signedAndEnvelopedData = new u("1.2.840.113549.1.7.4").C();
        digestedData = new u("1.2.840.113549.1.7.5").C();
        encryptedData = new u("1.2.840.113549.1.7.6").C();
        u uVar6 = new u("1.2.840.113549.1.9");
        pkcs_9 = uVar6;
        pkcs_9_at_emailAddress = uVar6.w("1").C();
        pkcs_9_at_unstructuredName = uVar6.w(ExifInterface.GPS_MEASUREMENT_2D).C();
        pkcs_9_at_contentType = uVar6.w(ExifInterface.GPS_MEASUREMENT_3D).C();
        pkcs_9_at_messageDigest = uVar6.w("4").C();
        pkcs_9_at_signingTime = uVar6.w("5").C();
        pkcs_9_at_counterSignature = uVar6.w("6").C();
        pkcs_9_at_challengePassword = uVar6.w("7").C();
        pkcs_9_at_unstructuredAddress = uVar6.w("8").C();
        pkcs_9_at_extendedCertificateAttributes = uVar6.w("9").C();
        pkcs_9_at_signingDescription = uVar6.w("13").C();
        pkcs_9_at_extensionRequest = uVar6.w("14").C();
        pkcs_9_at_smimeCapabilities = uVar6.w("15").C();
        u uVarC = uVar6.w("16").C();
        id_smime = uVarC;
        pkcs_9_at_binarySigningTime = uVar6.w("16.2.46").C();
        pkcs_9_at_friendlyName = uVar6.w("20").C();
        pkcs_9_at_localKeyId = uVar6.w("21").C();
        x509certType = uVar6.w("22.1");
        u uVarW = uVar6.w("22");
        certTypes = uVarW;
        x509Certificate = uVarW.w("1").C();
        sdsiCertificate = uVarW.w(ExifInterface.GPS_MEASUREMENT_2D).C();
        u uVarW2 = uVar6.w("23");
        crlTypes = uVarW2;
        x509Crl = uVarW2.w("1").C();
        id_aa_cmsAlgorithmProtect = uVar6.w("52").C();
        preferSignedData = uVar6.w("15.1");
        canNotDecryptAny = uVar6.w("15.2");
        sMIMECapabilitiesVersions = uVar6.w("15.3");
        u uVar7 = new u("1.2.840.113549.1.9.16.1");
        id_ct = uVar7;
        id_ct_authData = uVar7.w(ExifInterface.GPS_MEASUREMENT_2D);
        id_ct_TSTInfo = uVar7.w("4");
        id_ct_compressedData = uVar7.w("9");
        id_ct_authEnvelopedData = uVar7.w("23");
        id_ct_timestampedData = uVar7.w("31");
        u uVarW3 = uVarC.w(ExifInterface.GPS_MEASUREMENT_3D);
        id_alg = uVarW3;
        id_alg_PWRI_KEK = uVarW3.w("9");
        id_rsa_KEM = uVarW3.w("14");
        id_alg_hss_lms_hashsig = uVarW3.w("17");
        id_alg_AEADChaCha20Poly1305 = uVarW3.w("18");
        id_alg_hkdf_with_sha256 = uVarW3.w("28");
        id_alg_hkdf_with_sha384 = uVarW3.w("29");
        id_alg_hkdf_with_sha512 = uVarW3.w("30");
        u uVar8 = new u("1.2.840.113549.1.9.16.6");
        id_cti = uVar8;
        id_cti_ets_proofOfOrigin = uVar8.w("1");
        id_cti_ets_proofOfReceipt = uVar8.w(ExifInterface.GPS_MEASUREMENT_2D);
        id_cti_ets_proofOfDelivery = uVar8.w(ExifInterface.GPS_MEASUREMENT_3D);
        id_cti_ets_proofOfSender = uVar8.w("4");
        id_cti_ets_proofOfApproval = uVar8.w("5");
        id_cti_ets_proofOfCreation = uVar8.w("6");
        u uVar9 = new u("1.2.840.113549.1.9.16.2");
        id_aa = uVar9;
        id_aa_receiptRequest = uVar9.w("1");
        id_aa_contentHint = uVar9.w("4");
        id_aa_msgSigDigest = uVar9.w("5");
        id_aa_contentReference = uVar9.w("10");
        id_aa_encrypKeyPref = uVar9.w("11");
        id_aa_signingCertificate = uVar9.w("12");
        id_aa_signingCertificateV2 = uVar9.w("47");
        id_aa_contentIdentifier = uVar9.w("7");
        id_aa_signatureTimeStampToken = uVar9.w("14");
        u uVarW4 = uVar9.w("15");
        id_aa_ets_sigPolicyId = uVarW4;
        u uVarW5 = uVar9.w("16");
        id_aa_ets_commitmentType = uVarW5;
        u uVarW6 = uVar9.w("17");
        id_aa_ets_signerLocation = uVarW6;
        id_aa_ets_signerAttr = uVar9.w("18");
        u uVarW7 = uVar9.w("19");
        id_aa_ets_otherSigCert = uVarW7;
        id_aa_ets_contentTimestamp = uVar9.w("20");
        id_aa_ets_certificateRefs = uVar9.w("21");
        id_aa_ets_revocationRefs = uVar9.w("22");
        id_aa_ets_certValues = uVar9.w("23");
        id_aa_ets_revocationValues = uVar9.w("24");
        id_aa_ets_escTimeStamp = uVar9.w("25");
        id_aa_ets_certCRLTimestamp = uVar9.w("26");
        id_aa_ets_archiveTimestamp = uVar9.w("27");
        id_aa_decryptKeyID = uVar9.w("37");
        id_aa_implCryptoAlgs = uVar9.w("38");
        id_aa_asymmDecryptKeyID = uVar9.w("54");
        id_aa_implCompressAlgs = uVar9.w("43");
        id_aa_communityIdentifiers = uVar9.w("40");
        id_aa_sigPolicyId = uVarW4;
        id_aa_commitmentType = uVarW5;
        id_aa_signerLocation = uVarW6;
        id_aa_otherSigCert = uVarW7;
        id_spq_ets_uri = new u("1.2.840.113549.1.9.16.5.1");
        id_spq_ets_unotice = new u("1.2.840.113549.1.9.16.5.2");
        u uVar10 = new u("1.2.840.113549.1.12");
        pkcs_12 = uVar10;
        u uVarW8 = uVar10.w("10.1");
        bagtypes = uVarW8;
        keyBag = uVarW8.w("1");
        pkcs8ShroudedKeyBag = uVarW8.w(ExifInterface.GPS_MEASUREMENT_2D);
        certBag = uVarW8.w(ExifInterface.GPS_MEASUREMENT_3D);
        crlBag = uVarW8.w("4");
        secretBag = uVarW8.w("5");
        safeContentsBag = uVarW8.w("6");
        u uVarW9 = uVar10.w("1");
        pkcs_12PbeIds = uVarW9;
        pbeWithSHAAnd128BitRC4 = uVarW9.w("1");
        pbeWithSHAAnd40BitRC4 = uVarW9.w(ExifInterface.GPS_MEASUREMENT_2D);
        pbeWithSHAAnd3_KeyTripleDES_CBC = uVarW9.w(ExifInterface.GPS_MEASUREMENT_3D);
        pbeWithSHAAnd2_KeyTripleDES_CBC = uVarW9.w("4");
        pbeWithSHAAnd128BitRC2_CBC = uVarW9.w("5");
        pbeWithSHAAnd40BitRC2_CBC = uVarW9.w("6");
        pbewithSHAAnd40BitRC2_CBC = uVarW9.w("6");
        id_alg_CMS3DESwrap = new u("1.2.840.113549.1.9.16.3.6");
        id_alg_CMSRC2wrap = new u("1.2.840.113549.1.9.16.3.7");
        id_alg_ESDH = new u("1.2.840.113549.1.9.16.3.5");
        id_alg_SSDH = new u("1.2.840.113549.1.9.16.3.10");
    }
}
