.class public final Loa/q$a;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Loa/q;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "a"
.end annotation


# instance fields
.field private autoGenerated:Ljava/lang/Boolean;

.field private content:Ljava/lang/String;

.field private deliveryMethod:Loa/d;

.field private id:Ljava/lang/String;

.field private isUrl:Z

.field private languageCode:Ljava/lang/String;

.field private manifestUrl:Ljava/lang/String;

.field private mediaFormat:Lx9/m;


# direct methods
.method public constructor <init>()V
    .locals 1

    .line 1
    .line 2
    .line 3
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 4
    .line 5
    sget-object v0, Loa/d;->PROGRESSIVE_HTTP:Loa/d;

    .line 6
    .line 7
    iput-object v0, p0, Loa/q$a;->deliveryMethod:Loa/d;

    .line 8
    return-void
.end method


# virtual methods
.method public a()Loa/q;
    .locals 11
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Laa/h;
        }
    .end annotation

    .line 1
    .line 2
    iget-object v0, p0, Loa/q$a;->content:Ljava/lang/String;

    .line 3
    .line 4
    if-eqz v0, :cond_5

    .line 5
    .line 6
    iget-object v0, p0, Loa/q$a;->deliveryMethod:Loa/d;

    .line 7
    .line 8
    if-eqz v0, :cond_4

    .line 9
    .line 10
    iget-object v0, p0, Loa/q$a;->languageCode:Ljava/lang/String;

    .line 11
    .line 12
    if-eqz v0, :cond_3

    .line 13
    .line 14
    iget-object v1, p0, Loa/q$a;->autoGenerated:Ljava/lang/Boolean;

    .line 15
    .line 16
    if-eqz v1, :cond_2

    .line 17
    .line 18
    iget-object v1, p0, Loa/q$a;->id:Ljava/lang/String;

    .line 19
    .line 20
    if-nez v1, :cond_1

    .line 21
    .line 22
    iget-object v1, p0, Loa/q$a;->mediaFormat:Lx9/m;

    .line 23
    .line 24
    if-eqz v1, :cond_0

    .line 25
    .line 26
    iget-object v1, v1, Lx9/m;->suffix:Ljava/lang/String;

    .line 27
    .line 28
    new-instance v2, Ljava/lang/StringBuilder;

    .line 29
    .line 30
    .line 31
    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V

    .line 32
    .line 33
    const-string v3, "."

    .line 34
    .line 35
    .line 36
    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    .line 37
    .line 38
    .line 39
    invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    .line 40
    .line 41
    .line 42
    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    .line 43
    move-result-object v1

    .line 44
    goto :goto_0

    .line 45
    .line 46
    :cond_0
    const-string v1, ""

    .line 47
    .line 48
    :goto_0
    new-instance v2, Ljava/lang/StringBuilder;

    .line 49
    .line 50
    .line 51
    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V

    .line 52
    .line 53
    .line 54
    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    .line 55
    .line 56
    .line 57
    invoke-virtual {v2, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    .line 58
    .line 59
    .line 60
    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    .line 61
    move-result-object v0

    .line 62
    .line 63
    iput-object v0, p0, Loa/q$a;->id:Ljava/lang/String;

    .line 64
    .line 65
    :cond_1
    new-instance v0, Loa/q;

    .line 66
    .line 67
    iget-object v2, p0, Loa/q$a;->id:Ljava/lang/String;

    .line 68
    .line 69
    iget-object v3, p0, Loa/q$a;->content:Ljava/lang/String;

    .line 70
    .line 71
    iget-boolean v4, p0, Loa/q$a;->isUrl:Z

    .line 72
    .line 73
    iget-object v5, p0, Loa/q$a;->mediaFormat:Lx9/m;

    .line 74
    .line 75
    iget-object v6, p0, Loa/q$a;->deliveryMethod:Loa/d;

    .line 76
    .line 77
    iget-object v7, p0, Loa/q$a;->languageCode:Ljava/lang/String;

    .line 78
    .line 79
    iget-object v1, p0, Loa/q$a;->autoGenerated:Ljava/lang/Boolean;

    .line 80
    .line 81
    .line 82
    invoke-virtual {v1}, Ljava/lang/Boolean;->booleanValue()Z

    .line 83
    move-result v8

    .line 84
    .line 85
    iget-object v9, p0, Loa/q$a;->manifestUrl:Ljava/lang/String;

    .line 86
    const/4 v10, 0x0

    .line 87
    move-object v1, v0

    .line 88
    .line 89
    .line 90
    invoke-direct/range {v1 .. v10}, Loa/q;-><init>(Ljava/lang/String;Ljava/lang/String;ZLx9/m;Loa/d;Ljava/lang/String;ZLjava/lang/String;Loa/r;)V

    .line 91
    return-object v0

    .line 92
    .line 93
    :cond_2
    new-instance v0, Ljava/lang/IllegalStateException;

    .line 94
    .line 95
    const-string v1, "The subtitles stream has been not set as an autogenerated subtitles stream or not. Please specify this information with setIsAutoGenerated."

    .line 96
    .line 97
    .line 98
    invoke-direct {v0, v1}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V

    .line 99
    throw v0

    .line 100
    .line 101
    :cond_3
    new-instance v0, Ljava/lang/IllegalStateException;

    .line 102
    .line 103
    const-string v1, "The language code of the subtitles stream has been not set or is null. Make sure you specified an non null language code with setLanguageCode."

    .line 104
    .line 105
    .line 106
    invoke-direct {v0, v1}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V

    .line 107
    throw v0

    .line 108
    .line 109
    :cond_4
    new-instance v0, Ljava/lang/IllegalStateException;

    .line 110
    .line 111
    const-string v1, "The delivery method of the subtitles stream has been set as null, which is not allowed. Pass a valid one instead withsetDeliveryMethod."

    .line 112
    .line 113
    .line 114
    invoke-direct {v0, v1}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V

    .line 115
    throw v0

    .line 116
    .line 117
    :cond_5
    new-instance v0, Ljava/lang/IllegalStateException;

    .line 118
    .line 119
    const-string v1, "No valid content was specified. Please specify a valid one with setContent."

    .line 120
    .line 121
    .line 122
    invoke-direct {v0, v1}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V

    .line 123
    throw v0
.end method

.method public b(Z)Loa/q$a;
    .locals 0

    .line 1
    .line 2
    .line 3
    invoke-static {p1}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    .line 4
    move-result-object p1

    .line 5
    .line 6
    iput-object p1, p0, Loa/q$a;->autoGenerated:Ljava/lang/Boolean;

    .line 7
    return-object p0
.end method

.method public c(Ljava/lang/String;Z)Loa/q$a;
    .locals 0

    .line 1
    iput-object p1, p0, Loa/q$a;->content:Ljava/lang/String;

    iput-boolean p2, p0, Loa/q$a;->isUrl:Z

    return-object p0
.end method

.method public d(Ljava/lang/String;)Loa/q$a;
    .locals 0

    .line 1
    iput-object p1, p0, Loa/q$a;->languageCode:Ljava/lang/String;

    return-object p0
.end method

.method public e(Lx9/m;)Loa/q$a;
    .locals 0

    .line 1
    iput-object p1, p0, Loa/q$a;->mediaFormat:Lx9/m;

    return-object p0
.end method
