.class public final Loa/q;
.super Loa/g;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Loa/q$a;
    }
.end annotation


# instance fields
.field private final autoGenerated:Z

.field private final code:Ljava/lang/String;

.field private final format:Lx9/m;

.field private final locale:Ljava/util/Locale;


# direct methods
.method private constructor <init>(Ljava/lang/String;Ljava/lang/String;ZLx9/m;Loa/d;Ljava/lang/String;ZLjava/lang/String;)V
    .locals 7
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Laa/h;
        }
    .end annotation

    move-object v0, p0

    move-object v1, p1

    move-object v2, p2

    move v3, p3

    move-object v4, p4

    move-object v5, p5

    move-object v6, p8

    .line 2
    invoke-direct/range {v0 .. v6}, Loa/g;-><init>(Ljava/lang/String;Ljava/lang/String;ZLx9/m;Loa/d;Ljava/lang/String;)V

    .line 3
    invoke-static {p6}, Lqa/f;->a(Ljava/lang/String;)Ljava/util/Optional;

    move-result-object p1

    new-instance p2, Loa/p;

    invoke-direct {p2, p6}, Loa/p;-><init>(Ljava/lang/String;)V

    invoke-static {p1, p2}, Lorg/schabi/newpipe/extractor/localization/f;->a(Ljava/util/Optional;Ljava/util/function/Supplier;)Ljava/lang/Object;

    move-result-object p1

    check-cast p1, Ljava/util/Locale;

    iput-object p1, p0, Loa/q;->locale:Ljava/util/Locale;

    iput-object p6, p0, Loa/q;->code:Ljava/lang/String;

    iput-object p4, p0, Loa/q;->format:Lx9/m;

    iput-boolean p7, p0, Loa/q;->autoGenerated:Z

    return-void
.end method

.method synthetic constructor <init>(Ljava/lang/String;Ljava/lang/String;ZLx9/m;Loa/d;Ljava/lang/String;ZLjava/lang/String;Loa/r;)V
    .locals 0

    .line 1
    invoke-direct/range {p0 .. p8}, Loa/q;-><init>(Ljava/lang/String;Ljava/lang/String;ZLx9/m;Loa/d;Ljava/lang/String;ZLjava/lang/String;)V

    return-void
.end method

.method public static synthetic f(Ljava/lang/String;)Laa/h;
    .locals 0

    .line 1
    invoke-static {p0}, Loa/q;->g(Ljava/lang/String;)Laa/h;

    move-result-object p0

    return-object p0
.end method

.method private static synthetic g(Ljava/lang/String;)Laa/h;
    .locals 3

    .line 1
    .line 2
    new-instance v0, Laa/h;

    .line 3
    .line 4
    new-instance v1, Ljava/lang/StringBuilder;

    .line 5
    .line 6
    .line 7
    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V

    .line 8
    .line 9
    const-string v2, "not a valid locale language code: "

    .line 10
    .line 11
    .line 12
    invoke-virtual {v1, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    .line 13
    .line 14
    .line 15
    invoke-virtual {v1, p0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    .line 16
    .line 17
    .line 18
    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    .line 19
    move-result-object p0

    .line 20
    .line 21
    .line 22
    invoke-direct {v0, p0}, Laa/h;-><init>(Ljava/lang/String;)V

    .line 23
    return-object v0
.end method


# virtual methods
.method public b(Loa/g;)Z
    .locals 2

    .line 1
    .line 2
    .line 3
    invoke-super {p0, p1}, Loa/g;->b(Loa/g;)Z

    .line 4
    move-result v0

    .line 5
    .line 6
    if-eqz v0, :cond_0

    .line 7
    .line 8
    instance-of v0, p1, Loa/q;

    .line 9
    .line 10
    if-eqz v0, :cond_0

    .line 11
    .line 12
    iget-object v0, p0, Loa/q;->code:Ljava/lang/String;

    .line 13
    .line 14
    check-cast p1, Loa/q;

    .line 15
    .line 16
    iget-object v1, p1, Loa/q;->code:Ljava/lang/String;

    .line 17
    .line 18
    .line 19
    invoke-virtual {v0, v1}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z

    .line 20
    move-result v0

    .line 21
    .line 22
    if-eqz v0, :cond_0

    .line 23
    .line 24
    iget-boolean v0, p0, Loa/q;->autoGenerated:Z

    .line 25
    .line 26
    iget-boolean p1, p1, Loa/q;->autoGenerated:Z

    .line 27
    .line 28
    if-ne v0, p1, :cond_0

    .line 29
    const/4 p1, 0x1

    .line 30
    goto :goto_0

    .line 31
    :cond_0
    const/4 p1, 0x0

    .line 32
    :goto_0
    return p1
.end method
